//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3D.Legacy.Launcher.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MBLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MBLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3D.Legacy.Launcher.Forms.MBLang", typeof(MBLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon 3D requires Microsoft .NET Framework 4.0.
        ///Please visit http://www.microsoft.com/en-us/download/details.aspx?id=17851 to download.
        ///Would you like to open the webpage now?.
        /// </summary>
        internal static string DotNetError {
            get {
                return ResourceManager.GetString("DotNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/en-us/download/details.aspx?id=17851.
        /// </summary>
        internal static string DotNetErrorLink {
            get {
                return ResourceManager.GetString("DotNetErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string DotNetErrorTitle {
            get {
                return ResourceManager.GetString("DotNetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new Launcher version is available!
        ///Would you like to update?.
        /// </summary>
        internal static string LauncherUpdateAvailable {
            get {
                return ResourceManager.GetString("LauncherUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is Available!.
        /// </summary>
        internal static string LauncherUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("LauncherUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to GitHub! Is Internet connection available?.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check Error!.
        /// </summary>
        internal static string NoInternetTitle {
            get {
                return ResourceManager.GetString("NoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; was not downloaded!
        ///Would you like to download it?.
        /// </summary>
        internal static string NotDownloaded {
            get {
                return ResourceManager.GetString("NotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Downloaded!.
        /// </summary>
        internal static string NotDownloadedTitle {
            get {
                return ResourceManager.GetString("NotDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon 3D requires OpenAL.
        ///Please visit https://www.openal.org/downloads/ to download.
        ///Would you like to open the webpage now?.
        /// </summary>
        internal static string OpenALError {
            get {
                return ResourceManager.GetString("OpenALError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.openal.org/downloads/.
        /// </summary>
        internal static string OpenALErrorLink {
            get {
                return ResourceManager.GetString("OpenALErrorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string OpenALErrorTitle {
            get {
                return ResourceManager.GetString("OpenALErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; is up to date!.
        /// </summary>
        internal static string ProfileUpToDate {
            get {
                return ResourceManager.GetString("ProfileUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string ProfileUpToDateTitle {
            get {
                return ResourceManager.GetString("ProfileUpToDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the [{0}] version to [{1}] (Yes) or would you like to download it as an independent version (No)?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is Available!.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
    }
}
